const data = [
  {
    imgSrc: '/images/banners/bestSellersBanner/1.png',
    imgAlt: 'First best seller image',
    feedbackAmount: '1',
    stars: 1,
    label: ['hit', 'new', 'percent'],
    title: 'Super title',
  },
  {
    imgSrc: '/images/banners/bestSellersBanner/2.png',
    imgAlt: 'Second best seller image',
    feedbackAmount: '2',
    stars: '2',
    label: ['hit', 'percent'],
    title: 'Назва',
  },
  {
    imgSrc: '/images/banners/bestSellersBanner/3.png',
    imgAlt: 'Third best seller image',
    feedbackAmount: '1',
    stars: '3',
    label: ['new', 'percent'],
    title: 'І ще назва',
  },
  {
    imgSrc: '/images/banners/bestSellersBanner/4.png',
    imgAlt: 'Fourth best seller image',
    feedbackAmount: '5',
    stars: '4',
    label: ['new', 'hit'],
    title: 'Назва',
  },
  {
    imgSrc: '/images/banners/bestSellersBanner/5.png',
    imgAlt: 'Fiveth best seller image',
    feedbackAmount: '5',
    stars: '5',
    label: ['hit', 'new'],
    title: 'Назва',
  },
  {
    imgSrc: '/images/banners/bestSellersBanner/6.png',
    imgAlt: 'Sixth best seller image',
    feedbackAmount: '5',
    title: 'Назва',
    stars: '5',
  },
  {
    imgSrc: '/images/banners/bestSellersBanner/7.png',
    imgAlt: 'Seventh best seller image',
    feedbackAmount: '5',
    title: 'Назва',
    stars: '5',
  },
  {
    imgSrc: '/images/banners/bestSellersBanner/8.png',
    imgAlt: 'Eighth best seller image',
    feedbackAmount: '5',
    title: 'Назва',
    stars: '5',
  },
];

export default data;
